S3_TOKENIZER_QUANTIZER = "s3_tokenizer_quantizer.onnx"
SPEAKER_ENCODER = "speaker_encoder.onnx"
REFERENCE_MEL_24K = "reference_mel_24k.onnx"
TOKEN_TO_MU = "token_to_mu.onnx"
FLOW_DECODER_MEANFLOW2 = "flow_decoder_meanflow2.onnx"
VOCODER_HIFT = "vocoder_hift.onnx"
